import Foundation
import Testing
@testable import FitMatch

/// Synthetic, server-approved evidence. Expected numbers below are literal
/// hand calculations, never generated by the production scoring engine.
@MainActor
struct FitMatchReleasePreparationTests {
    @Test func weightedOracleAgreesWithPreviewDetailAndCompletionPayload() throws {
        let fixture = ReleasePreparationOracle()
        let begin = try fixture.begin()
        let detail = try VNextComparisonEngineAdapter().analyze(begin)

        // M: (90*2 + 95*1.5 + 85 + 95)/5.5 = 91.3636 -> 91.
        // L: (80*2 + 90*1.5 + 70 + 85)/5.5 = 81.8181 -> 82.
        #expect(detail.analyses.map(\.productSizeID) == [fixture.betterID, fixture.worseID])
        #expect(detail.analyses.map(\.result.score) == [91, 82])
        #expect(detail.analyses.map(\.rank) == [1, 2])
        #expect(detail.recommended.result.comparedItems.map(\.signedDifference) == [2, -1, 3, 1])
        #expect(detail.recommended.result.comparedItems.map(\.absoluteDifference) == [2, 1, 3, 1])
        #expect(detail.recommended.result.comparedItems.map(\.score) == [90, 95, 85, 95])
        #expect(abs(detail.recommended.result.averageDifference - 1.7272727272727273) < 0.000001)
        #expect(detail.completionPayload.recommendedProductSizeID == fixture.betterID)
        #expect(detail.completionPayload.score == 91)
        #expect(detail.completionPayload.reliability == 4)
        #expect(detail.completionPayload.coverage == 1)
        #expect(detail.completionPayload.metricEvidence.count == 8)

        let preview = try fixture.preview(begin)
        let candidate = FitMatchServerReferenceSelectionCandidate(
            comparisonPreview: preview, clientItemID: UUID(), closetItemID: fixture.closetID,
            comparisonGroupCode: "A", decision: .manualSelection, allowed: true,
            reasonCode: nil, reason: nil, commonMeasurementCount: 4
        )
        let group = try #require(FitMatchComparisonGroup(rawValue: "A"))
        let summary = try #require(RecommendationService().makeServerClosetComparisonBatchSummary(
            targetProductID: fixture.productID,
            comparisonGroup: group,
            candidates: [candidate]
        ).items.first)
        #expect(summary.recommendedProductSizeID == fixture.betterID)
        #expect(summary.similarityPercent == 91)
        #expect(summary.commonMeasurementCount == 4)
        // Both source labels are deliberately identical: identity must come
        // from the approved UUID rather than visible text or input order.
        #expect(detail.analyses.map(\.sizeLabel) == ["M", "M"])
    }

    @Test func partialOracleKeepsConfidenceSeparateFromCoverageAndSourceFacts() throws {
        let fixture = ReleasePreparationOracle()
        let begin = try fixture.begin(partial: true)
        let result = try VNextComparisonEngineAdapter().analyze(begin)

        // (90*2 + 100*1.5)/3.5 = 94.2857 -> 94; two of four
        // authorized policy dimensions are present, so confidence=2, coverage=.5.
        #expect(result.recommended.result.score == 94)
        #expect(result.completionPayload.reliability == 2)
        #expect(result.completionPayload.coverage == 0.5)
        #expect(result.recommended.result.comparedItems.map(\.signedDifference) == [2, 0])
        #expect(abs(result.recommended.result.averageDifference - 1.1428571428571428) < 0.000001)
        #expect(result.completionPayload.metricEvidence.map(\.measurementCode) == ["chest_width", "shoulder_width"])
        #expect(result.completionPayload.recommendedProductSizeID == fixture.betterID)
    }

    @Test func identicalScoreAndDeltaUseExactUUIDTieBreakIndependentOfInputOrder() throws {
        let fixture = ReleasePreparationOracle()
        let forward = try VNextComparisonEngineAdapter().analyze(fixture.begin(tied: true))
        let reversed = try VNextComparisonEngineAdapter().analyze(fixture.begin(tied: true, reversed: true))
        #expect(forward.analyses.map(\.productSizeID) == [fixture.betterID, fixture.worseID])
        #expect(reversed.analyses.map(\.productSizeID) == [fixture.betterID, fixture.worseID])
        #expect(forward.analyses.map(\.result.score) == [91, 91])
        #expect(reversed.completionPayload.candidateSizeRanking == forward.completionPayload.candidateSizeRanking)
    }

    @Test func inconsistentSignedDifferenceCannotProduceAnOracleResult() throws {
        let fixture = ReleasePreparationOracle()
        let corrupt = try fixture.begin(corruptDifference: true)
        #expect(throws: (any Error).self) {
            try VNextComparisonEngineAdapter().analyze(corrupt)
        }
    }

    // CHARACTERIZATION only: formula, half rounding and tie policy remain
    // UNRESOLVED. These literal hand calculations are not product approval.
    @Test func perItemHalfRoundsBeforeWeightedMean() throws {
        let fixture = ReleasePreparationOracle()
        let begin = try fixture.boundaryBegin(
            candidates: [(fixture.betterID, [0.5, -1.5])], metricIndices: [0, 1])
        let result = try VNextComparisonEngineAdapter().analyze(begin)
        // 97.5 -> 98; 92.5 -> 93; (98*2 + 93*1.5)/3.5 = 95.857... -> 96.
        // Averaging the unrounded items instead would produce 95, so parity
        // between two callers alone would not catch this regression.
        #expect(result.recommended.result.comparedItems.map(\.score) == [98, 93])
        #expect(result.recommended.result.score == 96)
        #expect(result.completionPayload.score == 96)
        #expect(result.completionPayload.metricEvidence.map(\.difference) == [0.5, -1.5])
        #expect(result.completionPayload.metricEvidence.map(\.absoluteDifference) == [0.5, 1.5])
        #expect(result.completionPayload.metricEvidence.map(\.targetValue) == [50.5, 46.5])
    }

    @Test func weightedMeanHalfRoundsAfterIntegerItemScores() throws {
        let fixture = ReleasePreparationOracle()
        let begin = try fixture.boundaryBegin(
            candidates: [(fixture.betterID, [0, 4, -2])], metricIndices: [0, 2, 3])
        let result = try VNextComparisonEngineAdapter().analyze(begin)
        // (100*2 + 80 + 90)/4 = 92.5 -> 93, with no per-item half boundary.
        #expect(result.recommended.result.comparedItems.map(\.score) == [100, 80, 90])
        #expect(result.recommended.result.score == 93)
        #expect(result.completionPayload.score == 93)
        #expect(result.completionPayload.reliability == 3)
        #expect(result.completionPayload.coverage == 0.75)
        #expect(result.completionPayload.metricEvidence.map(\.difference) == [0, 4, -2])
        #expect(result.completionPayload.metricEvidence.map(\.weight) == [2, 1, 1])
    }

    @Test func scoreEndpointsClampBelowZeroAndPreserveLargeDeltaEvidence() throws {
        let fixture = ReleasePreparationOracle()
        let thirdID = UUID(uuidString: "40000000-0000-0000-0000-000000000003")!
        let begin = try fixture.boundaryBegin(candidates: [
            (thirdID, [21]), (fixture.worseID, [20]), (fixture.betterID, [0])
        ])
        let result = try VNextComparisonEngineAdapter().analyze(begin)
        // 100 - 5*[0,20,21] = [100,0,-5], bounded to [100,0,0].
        #expect(result.analyses.map(\.productSizeID) == [fixture.betterID, fixture.worseID, thirdID])
        #expect(result.analyses.map(\.result.score) == [100, 0, 0])
        #expect(result.analyses.map(\.result.averageDifference) == [0, 20, 21])
        #expect(result.completionPayload.score == 100)
        #expect(result.completionPayload.candidateSizeRanking.map(\.score) == [100, 0, 0])
        // Completion evidence retains authorized input order and original
        // differences even when the score was clamped to zero.
        #expect(result.completionPayload.metricEvidence.map(\.productSizeID) == [thirdID, fixture.worseID, fixture.betterID])
        #expect(result.completionPayload.metricEvidence.map(\.difference) == [21, 20, 0])
        #expect(result.completionPayload.metricEvidence.map(\.targetValue) == [71, 70, 50])
    }

    @Test func equalScoreUsesWeightedDeltaBeforeExactUUID() throws {
        let fixture = ReleasePreparationOracle()
        let candidates: [(UUID, [Double])] = [(fixture.betterID, [-0.5, 0]), (fixture.worseID, [0, 0.5])]
        let forward = try VNextComparisonEngineAdapter().analyze(
            fixture.boundaryBegin(candidates: candidates, metricIndices: [0, 1]))
        let reversed = try VNextComparisonEngineAdapter().analyze(
            fixture.boundaryBegin(candidates: Array(candidates.reversed()), metricIndices: [0, 1]))
        // UUID1: 346/3.5 -> 99, delta 1/3.5; UUID2: 347/3.5 -> 99,
        // delta .75/3.5. UUID2 wins despite its lexicographically larger ID.
        #expect(forward.analyses.map(\.result.score) == [99, 99])
        #expect(forward.analyses.map(\.productSizeID) == [fixture.worseID, fixture.betterID])
        #expect(abs(forward.analyses[0].result.averageDifference - 0.21428571428571427) < 0.000001)
        #expect(abs(forward.analyses[1].result.averageDifference - 0.2857142857142857) < 0.000001)
        #expect(forward.completionPayload.recommendedProductSizeID == fixture.worseID)
        #expect(reversed.completionPayload.candidateSizeRanking == forward.completionPayload.candidateSizeRanking)
        #expect(forward.completionPayload.metricEvidence.map(\.difference) == [-0.5, 0, 0, 0.5])
        #expect(reversed.completionPayload.metricEvidence.map(\.difference) == [0, 0.5, -0.5, 0])
    }

    @Test func negativeAbsoluteEvidenceCannotBecomeAnAboveHundredScore() throws {
        let fixture = ReleasePreparationOracle()
        let invalid = try fixture.boundaryBegin(
            candidates: [(fixture.betterID, [0.5])], absoluteDifferenceOverride: -0.5)
        #expect(throws: VNextComparisonEngineAdapterError.invalidEvidence(fixture.betterID)) {
            try VNextComparisonEngineAdapter().analyze(invalid)
        }
    }
}

private struct ReleasePreparationOracle {
    let productID = UUID(uuidString: "10000000-0000-0000-0000-000000000001")!
    let variantID = UUID(uuidString: "20000000-0000-0000-0000-000000000001")!
    let closetID = UUID(uuidString: "30000000-0000-0000-0000-000000000001")!
    let betterID = UUID(uuidString: "40000000-0000-0000-0000-000000000001")!
    let worseID = UUID(uuidString: "40000000-0000-0000-0000-000000000002")!
    let codes = ["chest_width", "shoulder_width", "back_length", "sleeve_length"]
    let weights = [2.0, 1.5, 1.0, 1.0]

    func begin(partial: Bool = false, tied: Bool = false, reversed: Bool = false,
               corruptDifference: Bool = false) throws -> VNextBeginComparisonDTO {
        try JSONDecoder().decode(VNextBeginComparisonDTO.self, from: JSONSerialization.data(
            withJSONObject: beginObject(partial: partial, tied: tied, reversed: reversed,
                                       corruptDifference: corruptDifference)))
    }

    /// Only supplies fixed test inputs. Expected scores/deltas are literal in
    /// each test and in oracle-boundaries-v1.json, never calculated here.
    func boundaryBegin(candidates: [(UUID, [Double])], metricIndices: [Int] = [0],
                       absoluteDifferenceOverride: Double? = nil) throws -> VNextBeginComparisonDTO {
        try #require(candidates.allSatisfy { $0.1.count == metricIndices.count })
        var object = beginObject()
        var snapshot = try #require(object["snapshot"] as? [String: Any])
        var target = try #require(snapshot["target_snapshot"] as? [String: Any])
        var authorization = try #require(object["authorization"] as? [String: Any])
        authorization["common_measurement_count"] = metricIndices.count
        let references = [50.0, 48, 70, 60]
        let ids = candidates.map { $0.0.uuidString }
        target["authorized_candidate_product_size_ids"] = ids
        target["candidates"] = candidates.map { id, deltas -> [String: Any] in
            ["product_size_id": id.uuidString, "size_label": "M",
             "availability": ["status": "UNKNOWN"], "authorization": authorization,
             "comparison_measurements": zip(metricIndices, deltas).map { index, delta -> [String: Any] in
                 ["measurement_code": codes[index], "reference_value": references[index],
                  "target_value": references[index] + delta, "difference": delta,
                  "absolute_difference": absoluteDifferenceOverride ?? abs(delta), "weight": weights[index],
                  "unit_code": "CM", "basis_code": index < 2 ? "WIDTH" : "LENGTH",
                  "requirement_mode": "REQUIRED_ANY", "priority": index + 1]
             }]
        }
        snapshot["target_snapshot"] = target
        snapshot["authorization_snapshot"] = authorization
        object["snapshot"] = snapshot
        object["authorization"] = authorization
        object["authorized_candidate_product_size_ids"] = ids
        return try JSONDecoder().decode(VNextBeginComparisonDTO.self,
            from: JSONSerialization.data(withJSONObject: object))
    }

    private func beginObject(partial: Bool = false, tied: Bool = false, reversed: Bool = false,
                             corruptDifference: Bool = false) -> [String: Any] {
        let authorization: [String: Any] = [
            "decision": "MANUAL_EXTENDED", "allowed": true, "mode": "MANUAL_EXTENDED",
            "excluded_measurement_codes": [], "required_measurement_codes": ["chest_width"],
            "minimum_common": 1, "common_measurement_count": partial ? 2 : 4,
            "required_any_count": 1, "policy_code": "tshirt", "policy_version": "oracle-v1",
            "policy_checksum": "release-preparation-oracle"
        ]
        func candidate(_ id: UUID, values: [Double], deltas: [Double]) -> [String: Any] {
            let reference = [50.0, 48, 70, 60]
            return [
                "product_size_id": id.uuidString, "size_label": "M",
                "availability": ["status": "UNKNOWN"],
                "authorization": authorization,
                "comparison_measurements": values.indices.map { index -> [String: Any] in
                    ["measurement_code": codes[index], "reference_value": reference[index],
                     "target_value": values[index], "difference": corruptDifference && index == 0 ? 999 : deltas[index],
                     "absolute_difference": abs(deltas[index]), "weight": weights[index],
                     "unit_code": "CM", "basis_code": index < 2 ? "WIDTH" : "LENGTH",
                     "requirement_mode": "REQUIRED_ANY", "priority": index + 1]
                }
            ]
        }
        var candidates = partial
            ? [candidate(betterID, values: [52, 48], deltas: [2, 0])]
            : [candidate(worseID, values: tied ? [52, 47, 73, 61] : [54, 50, 76, 63],
                         deltas: tied ? [2, -1, 3, 1] : [4, 2, 6, 3]),
               candidate(betterID, values: [52, 47, 73, 61], deltas: [2, -1, 3, 1])]
        if reversed { candidates.reverse() }
        let ids = candidates.map { $0["product_size_id"] as! String }
        let policy: [String: Any] = [
            "policy_code": "tshirt", "policy_version": "oracle-v1", "policy_checksum": "release-preparation-oracle",
            "metrics": codes.indices.map { index -> [String: Any] in
                ["metric_mode": "CANONICAL", "fitmatch_measurement_code": codes[index],
                 "weight": weights[index], "requirement_mode": "REQUIRED_ANY", "priority": index + 1, "is_active": true]
            }
        ]
        let json: [String: Any] = [
            "comparison_id": "50000000-0000-0000-0000-000000000001", "created": true,
            "idempotent": false, "result_status": "PENDING", "authorization": authorization,
            "authorized_candidate_product_size_ids": ids, "candidate_authority_fingerprint": "oracle-candidates",
            "snapshot": [
                "snapshot_schema_version": 3, "reference_snapshot": ["closet_item_id": closetID.uuidString],
                "authority_snapshot": [:], "input_snapshot": [:], "excluded_measurement_codes": [],
                "policy_snapshot": policy, "authorization_snapshot": authorization,
                "target_snapshot": ["product_id": productID.uuidString, "variant_id": variantID.uuidString,
                    "classification_status": "CONFIRMED", "garment_type_code": "tshirt",
                    "authorized_candidate_product_size_ids": ids,
                    "candidate_authority_fingerprint": "oracle-candidates", "candidates": candidates]
            ]
        ]
        return json
    }

    func preview(_ begin: VNextBeginComparisonDTO) throws -> VNextEligibleCandidateSizesDTO {
        let snapshot = try #require(beginObject()["snapshot"] as? [String: Any])
        let target = try #require(snapshot["target_snapshot"] as? [String: Any])
        let encodedCandidates = try #require(target["candidates"])
        let json: [String: Any] = [
            "allowed": true, "decision": "MANUAL_EXTENDED", "mode": "MANUAL_EXTENDED", "manual_explicit": true,
            "reference_closet_item_id": closetID.uuidString, "target_product_id": productID.uuidString,
            "target_variant_id": variantID.uuidString,
            "authorized_candidate_product_size_ids": begin.authorizedCandidateProductSizeIDs.map(\.uuidString),
            "candidates": encodedCandidates
        ]
        return try JSONDecoder().decode(VNextEligibleCandidateSizesDTO.self,
            from: JSONSerialization.data(withJSONObject: json))
    }
}
