-- Column types captured from deployed DB; isolated fixture omits constraints, not a deployment baseline.
CREATE TABLE fitmatch_vnext.closet_item_measurements ("id" uuid,"closet_item_id" uuid,"source_measurement_code" text,"fitmatch_measurement_code" text,"value" numeric(14,4),"unit_code" text,"value_source" text,"raw_label_snapshot" text,"created_at" timestamp with time zone,"updated_at" timestamp with time zone,"source_measurement_code_snapshot" text);
CREATE TABLE fitmatch_vnext.closet_item_source_measurement_snapshots ("closet_item_id" uuid,"source_observation_id" uuid,"product_id" uuid,"product_variant_id" uuid,"product_size_id" uuid,"source_measurement_count" integer,"created_at" timestamp with time zone);
CREATE TABLE fitmatch_vnext.closet_item_source_measurements ("closet_item_id" uuid,"raw_measurement_key" text,"source_code" text,"parser_code" text,"raw_code" text,"raw_label" text,"raw_value" numeric,"raw_value_text" text,"raw_unit_code" text,"raw_representation" text,"source_measurement_code" text,"resolution_status" text,"mapping_version" text,"evidence_payload" jsonb,"source_observed_at" timestamp with time zone,"created_at" timestamp with time zone);
CREATE TABLE fitmatch_vnext.closet_items ("id" uuid,"user_id" uuid,"client_item_id" uuid,"product_id" uuid,"product_variant_id" uuid,"product_size_id" uuid,"item_name" text,"brand_name" text,"image_url" text,"product_url" text,"size_label" text,"audience_code" text,"garment_type_code" text,"sleeve_length_code" text,"lower_length_code" text,"body_length_code" text,"classification_source" text,"measurement_mode" text,"source_code_snapshot" text,"is_reference" boolean,"fit_preference_code" text,"notes" text,"created_at" timestamp with time zone,"updated_at" timestamp with time zone,"deleted_at" timestamp with time zone,"request_fingerprint" text,"classification_fingerprint" text,"classification_resolver_version" text,"satisfaction" smallint,"closet_detail_code_snapshot" text,"comparison_group_code" text,"comparison_group_source" text,"comparison_group_policy_version" text);
CREATE TABLE fitmatch_vnext.garment_types ("garment_type_code" text,"category_code" text,"comparison_policy_code" text,"display_name" text,"uses_sleeve_length" boolean,"uses_lower_length" boolean,"uses_body_length" boolean,"sort_order" integer,"is_active" boolean,"created_at" timestamp with time zone,"updated_at" timestamp with time zone);
CREATE TABLE fitmatch_vnext.product_sizes ("id" uuid,"variant_id" uuid,"source_size_key" text,"size_label" text,"normalized_size_label" text,"availability_status" text,"sort_order" integer,"last_seen_at" timestamp with time zone,"created_at" timestamp with time zone,"updated_at" timestamp with time zone);
CREATE TABLE fitmatch_vnext.product_variants ("id" uuid,"product_id" uuid,"source_variant_key" text,"variant_label" text,"color_code" text,"color_name" text,"image_url" text,"availability_status" text,"sort_order" integer,"last_seen_at" timestamp with time zone,"created_at" timestamp with time zone,"updated_at" timestamp with time zone);
CREATE TABLE fitmatch_vnext.products ("id" uuid,"source_code" text,"source_product_key" text,"product_name" text,"brand_name" text,"canonical_url" text,"image_url" text,"price_amount" numeric(14,2),"currency_code" text,"audience_code" text,"product_structure_code" text,"garment_type_code" text,"sleeve_length_code" text,"lower_length_code" text,"body_length_code" text,"classification_status" text,"classification_source" text,"classified_at" timestamp with time zone,"source_status" text,"source_extra" jsonb,"first_seen_at" timestamp with time zone,"last_seen_at" timestamp with time zone,"last_fetched_at" timestamp with time zone,"created_at" timestamp with time zone,"updated_at" timestamp with time zone,"primary_source_signal_id" uuid,"classification_mapping_id" uuid,"resolution_mode" text,"resolver_version" text,"input_fingerprint" text,"evidence_fingerprint" text,"classification_evidence" jsonb,"classification_reason" text,"override_reason" text,"override_evidence" jsonb,"override_actor_id" uuid,"override_authority_source" text,"override_version" text);
CREATE TABLE fitmatch_vnext.size_availability_observations ("id" bigint,"product_size_id" uuid,"source_code" text,"availability_status" text,"evidence_kind" text,"evidence_payload" jsonb,"evidence_fingerprint" text,"observed_at" timestamp with time zone,"valid_until" timestamp with time zone,"created_at" timestamp with time zone);